version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      expo:
        patterns:
          ['expo', 'expo-*', '@expo/*', 'react-native', 'react-native-*']
      firebase:
        patterns: ['firebase', 'firebase-*', '@firebase/*']
    versioning-strategy: increase-if-necessary

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
