packages:
  - apps/*
  - packages/*
  - functions

allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  re2: true
  sharp: true

minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.1'
  - '@vitest/spy@5.0.1'
  - firebase-tools@15.30.1
  - vitest@5.0.1
  - '@expo/cli@57.0.25'
  - '@expo/router-server@57.0.10'
  - babel-preset-expo@57.0.12
  - expo@57.0.23
